# Base configuration file for site settings.
# All entries in here will show up under {{ site.* }}

# Default metadata
title: Project Pages Template
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
lang: en
use-page-title: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "base"
      show-description: true

# Easy SEO
plugins:
  - jekyll-seo-tag

# Predefine footer tags
# Icons here are taken from simpleicons
footer:
  related-sites:
    sites:
      - text: Project Pages Demo
        href: https://buildingatom.io/project-pages/
        icon: icloud # Just using this for now
        icon-library: simpleicons

# Add credits to the bottom of the page
show-credit: true
credit:
  copyright-symbol: false
  text: >- # supports markdown
    [Project pages template](https://www.github.com/BuildingAtom/project-pages)
    built by Adam Li / [@BuildingAtom](https://www.github.com/BuildingAtom)

# Code highlighter
highlighter: rouge

# Enabled icon libraries
# Simpleicons doesn't need anything loaded.
icon-libraries:
  - bootstrap-icons
  - css.gg
  - ionicons
  - feathericons
  - academicons

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
