# Base configuration file for site settings.
# All entries in here will show up under {{ site.* }}

# Default metadata
title: Project Pages Template
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
lang: en
use-page-title: false

# Easy SEO
plugins:
  - jekyll-seo-tag

# Predefine footer tags
# Icons here are taken from simpleicons
footer:
  connections-pre: Lab Socials
  connections-post: Lab Socials
  connections:
    twitter: https://www.twitter.com/BuildingAtom
    github:  https://github.com/BuildingAtom
  related-sites:
    prefix-text:
    sites:
      - text: Demo site
        href: https://buildingatom.io/
        icon: gg-website
        icon-library: css.gg

# Add credits to the bottom of the page
show-credit: true
credit:
  copyright-symbol: true
  text: >- # supports markdown
    [Project pages template](https://www.github.com/BuildingAtom/project-pages)
    by Adam Li / [@BuildingAtom](https://www.github.com/BuildingAtom)

# Code highlighter
highlighter: rouge

# Enabled icon libraries
# Simpleicons doesn't need anything loaded.
icon-libraries:
  - bootstrap-icons
  - css.gg
  - ionicons
  - feathericons
  - academicons

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
