# User configuration file
# Values in this file will override values from the base_config.yml

# Metadata and SEO-helper stuff
# This title here should correspond to your base site or as a shared title
title: Project Pages Template
baseurl: "/project-pages" # the subpath of your site, e.g. /blog
url: "https://buildingatom.io" # the base hostname & protocol for your site, e.g. http://example.com
title-format: page-site # options are page-site, page, site

# Important for initial setup
plugins:
  - jekyll-seo-tag        # Easy SEO
  - jekyll-remote-theme   # So we can use the theme
  - jekyll-default-layout # So we can use the theme easily
remote_theme: BuildingAtom/project-pages@v1

# Hide the credits in the footer by setting this false.
show-credit: true

# Disable the footer by just setting the above false AND making the below blank
footer:
  connections-post: Socials
  connections:
    twitter: https://www.twitter.com/BuildingAtom
    github:  https://github.com/BuildingAtom
  related-sites:
    sites:
      - text: SEL Map Example
        href: /project-pages/sel_map
        icon: bi-map
        icon-library: bootstrap-icons
      - text: ARMOUR Example
        href: /project-pages/armour-dev
        icon: bi-bezier2
        icon-library: bootstrap-icons


# Only leave the icon libraries you want to use enabled.
# The supported libraries are:
# bootstrap-icons, css.gg, ionicons, feathericons, academicons
#
# simpleicons is also supported, but doesn't need to be listed as
# it doesn't require any extra loading.
# Default is to load all of the above.
icon-libraries:
  - bootstrap-icons

# There is room for extra SEO shenanigans. jekyll-seo-tag is included,
# so check out that repo to see what you can do.
